#!/bin/sh
#
# Check that the estimated time counter counts.

dd if=/dev/zero bs=100 count=1 2>/dev/null \
| $PROG -f -e -s 100 -i 0.1 -L 25 >/dev/null 2>$TMP1
NUM=`tr '\r' '\n' < $TMP1 | sed '/^$/d' | sort | uniq | wc -l | tr -d ' '`
test $NUM -gt 3 && test $NUM -lt 5

# EOF
