#!/bin/sh
#
# Check that dd doesn't cause a SIGPIPE.

COUNT1=`cat /dev/zero | dd bs=100000 count=1000 2>/dev/null | wc -c`
COUNT2=`$PROG -B 100000 -q /dev/zero | dd bs=100000 count=1000 2>/dev/null | wc -c`

test "x$COUNT1" = "x$COUNT2"

# EOF
