#!/bin/sh
#
# Check that the byte counter counts.
#
# $Id$

dd if=/dev/zero bs=100 count=1 2>/dev/null \
| $PROG -f -b >/dev/null 2>$TMP1
NUM=`tr '\r' '\n' < $TMP1 | tr -d ' '`
test "$NUM" = "100B"

# EOF $Id$
